apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: zeus-core
  namespace: ac-agentic
  labels:
    app: zeus-core
    component: api
spec:
  output:
    to:
      kind: ImageStreamTag
      name: zeus-core:latest
  source:
    type: Git
    git:
      uri: 'https://github.com/vicktorf/zeus-nexus.git'
      ref: main
    contextDir: docker
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile.zeus-core
  triggers:
    - type: ConfigChange
    - type: ImageChange

---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: zeus-core
  namespace: ac-agentic
  labels:
    app: zeus-core
    component: api